Repository github/VisualStudio, pull requests merged in 2018-07, with the labels that each got.

#1737 Refactoring PR list
  lib/Octokit.GraphQL.0.0.5-alpha.nupkg
  src/GitHub.Api/GitHub.Api.csproj
  src/GitHub.Api/packages.config
  src/GitHub.App/Collections/IVirtualizingListSource.cs
  src/GitHub.App/Collections/SequentialListSource.cs
  src/GitHub.App/Collections/VirtualizingList.cs
  src/GitHub.App/Collections/VirtualizingListCollectionView.cs
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/SampleData/ActorViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestListItemViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestListViewModelDesigner.cs
  src/GitHub.App/SampleData/UserFilterViewModelDesigner.cs
  src/GitHub.App/Services/PullRequestService.cs
  src/GitHub.App/Services/RepositoryService.cs
  src/GitHub.App/ViewModels/GitHubPane/IssueListViewModelBase.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestListItemViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestListViewModel.cs
  src/GitHub.App/ViewModels/UserFilterViewModel.cs
  src/GitHub.App/packages.config
  src/GitHub.Exports.Reactive/GitHub.Exports.Reactive.csproj
  src/GitHub.Exports.Reactive/Services/IPullRequestService.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IIssueListItemViewModelBase.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IIssueListViewModelBase.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestListItemViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestListViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/IUserFilterViewModel.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Models/Page.cs
  src/GitHub.Exports/Models/PullRequestListItemModel.cs
  src/GitHub.Exports/Services/IRepositoryService.cs
  src/GitHub.Exports/packages.config
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/packages.config
  src/GitHub.UI/Controls/DropDownButton.cs
  src/GitHub.UI/Controls/DropDownButton.xaml
  src/GitHub.UI/Controls/Octicons/OcticonImage.xaml
  src/GitHub.UI/Controls/Octicons/OcticonPaths.Designer.cs
  src/GitHub.UI/Controls/Octicons/OcticonPaths.resx
  src/GitHub.VisualStudio.UI/Resources.Designer.cs
  src/GitHub.VisualStudio.UI/Resources.resx
  src/GitHub.VisualStudio.UI/Styles/ItemsControls.xaml
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItem.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItemView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItemView.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListView.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestReviewSummaryView.xaml
  src/GitHub.VisualStudio/Views/UserFilterView.xaml
  src/GitHub.VisualStudio/Views/UserFilterView.xaml.cs
  src/GitHub.VisualStudio/packages.config
  test/GitHub.App.UnitTests/GitHub.App.UnitTests.csproj
  test/GitHub.App.UnitTests/Services/PullRequestServiceTests.cs
  test/GitHub.App.UnitTests/ViewModels/Dialog/PullRequestCreationViewModelTests.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/IssueListViewModelBaseTests.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/PullRequestListViewModelTests.cs
  test/GitHub.App.UnitTests/ViewModels/UserFilterViewModelTests.cs
  test/GitHub.App.UnitTests/packages.config
Labels: WIP

#1717 Enable spell checking where appropriate
  src/GitHub.InlineReviews/Views/CommentView.xaml
  src/GitHub.UI/Assets/Controls.xaml
  src/GitHub.UI/Assets/Controls/FilterTextBox.xaml
  src/GitHub.UI/Assets/TextBlocks.xaml
  src/GitHub.VisualStudio/Views/Dialog/GistCreationView.xaml
  src/GitHub.VisualStudio/Views/Dialog/RepositoryCreationView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCreationView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestReviewAuthoringView.xaml
  src/GitHub.VisualStudio/Views/TeamExplorer/RepositoryPublishView.xaml
Labels: Ready for Review

#1772 Fix standalone comment replies
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/Services/PullRequestSessionService.cs
  src/GitHub.InlineReviews/packages.config
Labels: verified

#1771 Open from clipboard url
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/Services/GitHubContextService.cs
  src/GitHub.Exports/Commands/IOpenFromClipboardCommand.cs
  src/GitHub.Exports/Commands/IOpenFromUrlCommand.cs
  src/GitHub.Exports/Exports/ExportMetadata.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Primitives/UriString.cs
  src/GitHub.Exports/Services/GitHubContext.cs
  src/GitHub.Exports/Services/IGitHubContextService.cs
  src/GitHub.Exports/Services/IVSServices.cs
  src/GitHub.Exports/Services/VSServices.cs
  src/GitHub.Exports/Settings/PkgCmdID.cs
  src/GitHub.VisualStudio/Commands/OpenFromClipboardCommand.cs
  src/GitHub.VisualStudio/Commands/OpenFromUrlCommand.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/GitHub.VisualStudio.vsct
  src/GitHub.VisualStudio/GitHubPackage.cs
  src/GitHub.VisualStudio/packages.config
  test/GitHub.App.UnitTests/GitHub.App.UnitTests.csproj
  test/GitHub.App.UnitTests/Services/GitHubContextServiceTests.cs
  test/GitHub.Primitives.UnitTests/UriStringTests.cs
  test/GitHub.VisualStudio.UnitTests/Commands/OpenFromClipboardCommandTests.cs
  test/GitHub.VisualStudio.UnitTests/GitHub.VisualStudio.UnitTests.csproj
  test/GitHub.VisualStudio.UnitTests/packages.config
Labels: Ready for Review, verified

#1789 Fixing functionality to delete a pull request comment
  src/GitHub.Exports.Reactive/Services/IPullRequestSession.cs
  src/GitHub.Exports/Models/CommentModel.cs
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/SampleData/CommentViewModelDesigner.cs
  src/GitHub.InlineReviews/Services/IPullRequestSessionService.cs
  src/GitHub.InlineReviews/Services/InlineCommentPeekService.cs
  src/GitHub.InlineReviews/Services/PullRequestSession.cs
  src/GitHub.InlineReviews/Services/PullRequestSessionService.cs
  src/GitHub.InlineReviews/ViewModels/CommentViewModel.cs
  src/GitHub.InlineReviews/ViewModels/ICommentViewModel.cs
  src/GitHub.InlineReviews/ViewModels/InlineCommentPeekViewModel.cs
  src/GitHub.InlineReviews/ViewModels/InlineCommentThreadViewModel.cs
  src/GitHub.InlineReviews/ViewModels/PullRequestReviewCommentViewModel.cs
Labels: verified

#1793 Polish check suite results in pull request list
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItemView.xaml
Labels: Ready for Review

#1803 Bring the GitHub mark back into the menu (and start page)
  src/GitHub.VisualStudio/Resources/icons/mark_github.xaml
Labels: Ready for Review

#1813 Polish checks list in pull request details
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCheckView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestDetailView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItemView.xaml
Labels: Ready for Review, cosmetic
