Repository github/VisualStudio, pull requests merged in 2018-04, with the labels that each got.

#1545 Display Pull Request Reviews for a User.
  src/GitHub.App/Api/ApiClient.cs
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/Models/PullRequestReviewModel.cs
  src/GitHub.App/SampleData/PullRequestReviewFileCommentViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestReviewViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestUserReviewsViewModelDesigner.cs
  src/GitHub.App/Services/ModelService.cs
  src/GitHub.App/ViewModels/GitHubPane/GitHubPaneViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewFileCommentViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestUserReviewsViewModel.cs
  src/GitHub.Exports.Reactive/Api/IApiClient.cs
  src/GitHub.Exports.Reactive/GitHub.Exports.Reactive.csproj
  src/GitHub.Exports.Reactive/Services/IModelService.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestReviewFileCommentViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestReviewViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestUserReviewsViewModel.cs
  src/GitHub.Exports/Models/IPullRequestReviewModel.cs
  src/GitHub.Exports/ViewModels/GitHubPane/IGitHubPaneViewModel.cs
  src/GitHub.UI/Assets/Controls.xaml
  src/GitHub.UI/Controls/TrimmedPathTextBlock.cs
  src/GitHub.UI/Converters/TrimNewlinesConverter.cs
  src/GitHub.UI/GitHub.UI.csproj
  src/GitHub.VisualStudio.UI/Styles/ThemeBlue.xaml
  src/GitHub.VisualStudio.UI/Styles/ThemeDark.xaml
  src/GitHub.VisualStudio.UI/Styles/ThemeLight.xaml
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestFileCommentsView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestFileCommentsView.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestUserReviewsView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestUserReviewsView.xaml.cs
  test/UnitTests/GitHub.App/ViewModels/GitHubPane/PullRequestReviewViewModelTests.cs
  test/UnitTests/GitHub.App/ViewModels/GitHubPane/PullRequestUserReviewsViewModelTests.cs
  test/UnitTests/UnitTests.csproj
Labels: verified

#1569 Initialize GitHubPane and menus asynchronously
  src/GitHub.Exports/Settings/Guids.cs
  src/GitHub.InlineReviews/InlineReviewsPackage.cs
  src/GitHub.InlineReviews/PullRequestStatusBarPackage.cs
  src/GitHub.InlineReviews/Services/PullRequestStatusBarManager.cs
  src/GitHub.VisualStudio/Commands/ShowCurrentPullRequestCommand.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/GitHubPackage.cs
  src/GitHub.VisualStudio/GitHubPanePackage.cs
  src/GitHub.VisualStudio/UI/GitHubPane.cs
Labels: Ready for Review

#1567 Add PR reviews metrics.
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.InlineReviews/Services/PullRequestSessionService.cs
Labels: verified

#1580 Fix navigate to editor.
  src/GitHub.App/Services/PullRequestEditorService.cs
Labels: verified

#1581 Fix Octokit.GraphQL escaping issue.
  lib/.gitignore
  lib/Octokit.GraphQL.0.0.1.nupkg
  lib/Octokit.GraphQL.0.0.2-alpha.nupkg
  src/GitHub.Api/GitHub.Api.csproj
  src/GitHub.Api/packages.config
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/packages.config
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/packages.config
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/packages.config
  test/UnitTests/UnitTests.csproj
  test/UnitTests/packages.config
Labels: verified

#1586 Make avatar in PR review summary clickable.
  src/GitHub.VisualStudio.UI/UI/Controls/AccountAvatar.xaml
  src/GitHub.VisualStudio.UI/UI/Controls/AccountAvatar.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestReviewSummaryView.xaml
Labels: verified

#1430 Functionality to enable/disable trace logging
  src/GitHub.Exports/Settings/generated/IPackageSettings.cs
  src/GitHub.Logging/GitHub.Logging.csproj
  src/GitHub.Logging/Logging/LogManager.cs
  src/GitHub.Logging/packages.config
  src/GitHub.VisualStudio.UI/Resources.Designer.cs
  src/GitHub.VisualStudio.UI/Resources.resx
  src/GitHub.VisualStudio/GitHubPackage.cs
  src/GitHub.VisualStudio/Services/GitHubServiceProvider.cs
  src/GitHub.VisualStudio/Settings/OptionsPage.cs
  src/GitHub.VisualStudio/Settings/PackageSettings.cs
  src/GitHub.VisualStudio/Settings/generated/PackageSettingsGen.cs
  src/GitHub.VisualStudio/UI/Settings/OptionsControl.xaml
  src/GitHub.VisualStudio/UI/Settings/OptionsControl.xaml.cs
  src/common/settings.json
Labels: Ready for Review

#1579 Limit avatar download attempts
  src/GitHub.App/Services/ImageDownloader.cs
  test/UnitTests/GitHub.App/Services/ImageDownloaderTests.cs
  test/UnitTests/UnitTests.csproj
Labels: Ready for Review

#1577 Fix opening Pull Request on GitHub.
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItem.xaml
Labels: verified

#1267 Functionality to easily add new metrics
  src/GitHub.Exports/Models/UsageData.cs
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.Exports/Services/IUsageService.cs
  src/GitHub.Exports/Services/IUsageTracker.cs
  src/GitHub.Exports/Services/MetricsService.cs
  src/GitHub.VisualStudio/Services/UsageService.cs
  src/GitHub.VisualStudio/Services/UsageTracker.cs
  test/UnitTests/GitHub.App/Services/RepositoryCloneServiceTests.cs
  test/UnitTests/GitHub.VisualStudio/Services/MetricsTests.cs
  test/UnitTests/UnitTests.csproj
Labels: Ready for Review

#1552 Make Navigate to Editor more discoverable
  src/GitHub.App/Resources.Designer.cs
  src/GitHub.App/Resources.resx
  src/GitHub.App/Services/PullRequestEditorService.cs
Labels: Ready for Review, verified

#1606 Adding metrics tests for the new metrics
  GitHubVS.sln
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.Exports/Properties/AssemblyInfo.cs
  src/GitHub.Exports/Services/MetricsService.cs
  src/GitHub.VisualStudio/Services/UsageTracker.cs
  test/MetricsTests/MetricsServer/App.config
  test/MetricsTests/MetricsServer/MetricsServer.csproj
  test/MetricsTests/MetricsServer/Program.cs
  test/MetricsTests/MetricsServer/Properties/AssemblyInfo.cs
  test/MetricsTests/MetricsServer/key.snk
  test/MetricsTests/MetricsServer/packages.config
  test/MetricsTests/MetricsServerApp/App.config
  test/MetricsTests/MetricsServerApp/MetricsServerApp.csproj
  test/MetricsTests/MetricsServerApp/Program.cs
  test/MetricsTests/MetricsServerApp/Properties/AssemblyInfo.cs
  test/MetricsTests/MetricsTests.sln
  test/MetricsTests/MetricsTests/MetricsTests.cs
  test/MetricsTests/MetricsTests/MetricsTests.csproj
  test/MetricsTests/MetricsTests/Properties/AssemblyInfo.cs
  test/MetricsTests/MetricsTests/key.snk
  test/MetricsTests/MetricsTests/packages.config
  test/UnitTests/GitHub.App/Services/RepositoryCloneServiceTests.cs
  test/UnitTests/GitHub.VisualStudio/Services/MetricsTests.cs
Labels: Ready for Review

#1609 Fix avatar in inline comments.
  src/GitHub.VisualStudio.UI/UI/Controls/AccountAvatar.xaml
Labels: verified

#1611 Add metrics for Team Explorer -Home - Pull Requests button
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.TeamFoundation.14/Home/PullRequestsNavigationItem.cs
Labels: Ready for Review

#1593 Show `Pull requests` button on status bar when there's no active PR branch
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.InlineReviews/Services/PullRequestStatusBarManager.cs
  src/GitHub.InlineReviews/ViewModels/PullRequestStatusViewModel.cs
  src/GitHub.InlineReviews/Views/PullRequestStatusView.xaml
  src/GitHub.VisualStudio/Commands/ShowCurrentPullRequestCommand.cs
Labels: Ready for Review, verified
