Repository github/VisualStudio, pull requests merged in 2018-08, with the labels that each got.

#1808 Attempting to use the view locator correctly
  src/GitHub.App/ViewModels/GitHubPane/PullRequestCheckViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCheckView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCheckView.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestDetailView.xaml
Labels: Ready for Review

#1811 Fix to allow searching an issue by just number
  src/GitHub.App/ViewModels/GitHubPane/IssueListViewModelBase.cs
Labels: Ready for Review

#1825 Fix usernames not displayed in file comments
  src/GitHub.InlineReviews/Views/CommentView.xaml
Labels: Ready for Review

#1822 Show a confirmation when attempting to delete a comment
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/Peek/InlineCommentPeekableItemSource.cs
  src/GitHub.InlineReviews/Peek/InlineCommentPeekableItemSourceProvider.cs
  src/GitHub.InlineReviews/Services/CommentService.cs
  src/GitHub.InlineReviews/Services/ICommentService.cs
  src/GitHub.InlineReviews/ViewModels/CommentViewModel.cs
  src/GitHub.InlineReviews/ViewModels/InlineCommentPeekViewModel.cs
  src/GitHub.InlineReviews/ViewModels/InlineCommentThreadViewModel.cs
  src/GitHub.InlineReviews/ViewModels/NewInlineCommentThreadViewModel.cs
  src/GitHub.InlineReviews/ViewModels/PullRequestReviewCommentViewModel.cs
  src/GitHub.InlineReviews/Views/CommentView.xaml
  src/GitHub.UI/Controls/Buttons/OcticonButton.xaml
  src/GitHub.VisualStudio.UI/Resources.Designer.cs
  src/GitHub.VisualStudio.UI/Resources.resx
  test/GitHub.InlineReviews.UnitTests/ViewModels/InlineCommentPeekViewModelTests.cs
  test/GitHub.InlineReviews.UnitTests/ViewModels/InlineCommentThreadViewModelTests.cs
  test/GitHub.InlineReviews.UnitTests/ViewModels/NewInlineCommentThreadViewModelTests.cs
  test/GitHub.InlineReviews.UnitTests/ViewModels/PullRequestReviewCommentViewModelTests.cs
Labels: Ready for Review, cosmetic, usability

#1830 Sorting Pull Request reviews by date
  src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewSummaryViewModel.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/PullRequestDetailViewModelTests.cs
Labels: Ready for Review

#1805 Fixing incorrect casing in the clone url owner issues
  src/GitHub.App/Services/PullRequestService.cs
  src/GitHub.InlineReviews/Services/PullRequestSessionManager.cs
  test/GitHub.App.UnitTests/Services/PullRequestServiceTests.cs
  test/GitHub.InlineReviews.UnitTests/Services/PullRequestSessionManagerTests.cs
Labels: Ready for Review

#1835 Sorting PullRequestReviewState.Dismissed correctly
  src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewSummaryViewModel.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/PullRequestDetailViewModelTests.cs
Labels: Ready for Review

#1788 Pull Requests w/ Statuses
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/SampleData/PullRequestCheckViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestDetailViewModelDesigner.cs
  src/GitHub.App/SampleData/PullRequestListItemViewModelDesigner.cs
  src/GitHub.App/Services/PullRequestService.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestCheckViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestListItemViewModel.cs
  src/GitHub.Exports.Reactive/GitHub.Exports.Reactive.csproj
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestCheckViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestDetailViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/IPullRequestListItemViewModel.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Models/IPullRequestModel.cs
  src/GitHub.Exports/Models/PullRequestDetailModel.cs
  src/GitHub.Exports/Models/PullRequestListItemModel.cs
  src/GitHub.Exports/Models/StatusModel.cs
  src/GitHub.Exports/Models/StatusState.cs
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.InlineReviews/Services/PullRequestSessionService.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCheckView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestCheckView.xaml.cs
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestDetailView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestListItemView.xaml
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/PullRequestDetailViewModelTests.cs
Labels: Ready for Review

#1838 Adding functionality to confirm before cancelling a review
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/Resources.Designer.cs
  src/GitHub.App/Resources.resx
  src/GitHub.App/Services/PullRequestService.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewAuthoringViewModel.cs
  src/GitHub.Exports.Reactive/Services/IPullRequestService.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/PullRequestReviewAuthoringViewModelTests.cs
Labels: Ready for Review

#1844 Ignore zero width lines in document snapshot
  src/GitHub.VisualStudio/Helpers/ActiveDocumentSnapshot.cs
Labels: Ready for Review

#1845 Make publish repository description only accept a single line
  src/GitHub.VisualStudio/Views/TeamExplorer/RepositoryPublishView.xaml
Labels: Ready for Review

#1842 Style TreeViewItem
  src/GitHub.VisualStudio.UI/Styles/ItemsControls.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestDetailView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestFilesView.xaml
Labels: Ready for Review

#1854 Allow user to choose between creating GitHub or GitHub Enterprise Gist
  src/GitHub.App/Services/DialogService.cs
  src/GitHub.Exports/Commands/ICreateGistEnterpriseCommand.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Services/IDialogService.cs
  src/GitHub.Exports/Settings/PkgCmdID.cs
  src/GitHub.VisualStudio/Commands/CreateGistCommand.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.vsct
  src/GitHub.VisualStudio/GitHubPackage.cs
Labels: Ready for Review

#1839 Fix extension on versions of Visual Studio 2017 earlier than 15.4.4
  src/GitHub.TeamFoundation.15/GitHub.TeamFoundation.15.csproj
  src/GitHub.TeamFoundation.15/packages.config
Labels: Ready for Review

#1846 Repairing xml comments
  src/GitHub.Api/ILoginManager.cs
  src/GitHub.Api/LoginManager.cs
  src/GitHub.App/Extensions/AkavacheExtensions.cs
  src/GitHub.App/Services/PullRequestEditorService.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDirectoryNode.cs
  src/GitHub.Exports.Reactive/Services/IGitClient.cs
  src/GitHub.Exports.Reactive/Services/IPullRequestService.cs
  src/GitHub.Exports.Reactive/Services/IPullRequestSession.cs
  src/GitHub.Exports.Reactive/Services/IPullRequestSessionManager.cs
  src/GitHub.Exports.Reactive/Services/IRepositoryCloneService.cs
  src/GitHub.Exports.Reactive/Services/IShowDialogService.cs
  src/GitHub.Exports/Factories/IViewViewModelFactory.cs
  src/GitHub.Exports/Models/ILocalRepositoryModel.cs
  src/GitHub.Exports/Services/IGitHubContextService.cs
  src/GitHub.Exports/Services/IGitService.cs
  src/GitHub.Exports/Services/IVSGitServices.cs
  src/GitHub.Exports/Services/IVSServices.cs
  src/GitHub.InlineReviews/Commands/InlineCommentNavigationCommand.cs
  src/GitHub.InlineReviews/Models/InlineCommentThreadModel.cs
  src/GitHub.InlineReviews/Services/IDiffService.cs
  src/GitHub.InlineReviews/Services/IInlineCommentPeekService.cs
  src/GitHub.InlineReviews/Services/PullRequestSessionManager.cs
  src/GitHub.InlineReviews/ViewModels/PullRequestReviewCommentViewModel.cs
  src/GitHub.Services.Vssdk/Commands/MenuCommandServiceExtensions.cs
  src/GitHub.TeamFoundation.14/Base/TeamExplorerServiceHolder.cs
Labels: Ready for Review

#1873 Display default avatar for avatars from enterprise hosts.
  src/GitHub.App/ViewModels/ActorViewModel.cs
Labels: verified

#1853 Better failure modes
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/SampleData/SampleViewModels.cs
  src/GitHub.App/Services/StandardUserErrors.cs
  src/GitHub.App/ViewModels/GitHubPane/GitHubPaneViewModel.cs
  src/GitHub.App/ViewModels/GitHubPane/LoginFailedViewModel.cs
  src/GitHub.Exports.Reactive/GitHub.Exports.Reactive.csproj
  src/GitHub.Exports.Reactive/ViewModels/GitHubPane/ILoginFailedViewModel.cs
  src/GitHub.Exports/Models/IConnection.cs
  src/GitHub.Exports/Services/Connection.cs
  src/GitHub.Exports/Services/IConnectionManager.cs
  src/GitHub.Exports/Services/ITeamExplorerServices.cs
  src/GitHub.Exports/ViewModels/IGitHubConnectSection.cs
  src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection.cs
  src/GitHub.TeamFoundation.14/Connect/GitHubInvitationSection.cs
  src/GitHub.TeamFoundation.14/Services/TeamExplorerServices.cs
  src/GitHub.VisualStudio.UI/Resources.Designer.cs
  src/GitHub.VisualStudio.UI/Resources.resx
  src/GitHub.VisualStudio.UI/UI/Views/GitHubConnectContent.xaml
  src/GitHub.VisualStudio.UI/UI/Views/GitHubConnectContent.xaml.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/Services/ConnectionManager.cs
  src/GitHub.VisualStudio/Views/GitHubPane/LoginFailedView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/LoginFailedView.xaml.cs
  test/GitHub.App.UnitTests/ViewModels/GitHubPane/GitHubPaneViewModelTests.cs
  test/GitHub.VisualStudio.UnitTests/Services/ConnectionManagerTests.cs
Labels: Ready for Review, verified

#1890 Code coverage
  README.md
  appveyor.yml
  codecov.yml
Labels: Ready for Review
