Repository github/VisualStudio, pull requests merged in 2018-05, with the labels that each got.

#1642 Factor sync submodules into VS command
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  src/GitHub.Exports/Commands/ISyncSubmodulesCommand.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Settings/PkgCmdID.cs
  src/GitHub.VisualStudio/Commands/SyncSubmodulesCommand.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/GitHub.VisualStudio.vsct
  src/GitHub.VisualStudio/GitHubPackage.cs
  test/UnitTests/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModelTests.cs
Labels: Ready for Review, enhancement

#1656 Add separate metrics for StartPage/ConnectSection clones
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.StartPage/StartPagePackage.cs
  src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection.cs
  src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection0.cs
  src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection1.cs
Labels: Ready for Review

#1568 Allow user to toggle inline comment margin
  src/GitHub.App/Commands/UsageTrackingCommand.cs
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/Resources.Designer.cs
  src/GitHub.App/Services/PullRequestEditorService.cs
  src/GitHub.App/Services/TextViewCommandDispatcher.cs
  src/GitHub.App/ViewModels/GitHubPane/PullRequestFilesViewModel.cs
  src/GitHub.Exports.Reactive/Services/IPullRequestEditorService.cs
  src/GitHub.Exports/Commands/IGoToSolutionOrPullRequestFileCommand.cs
  src/GitHub.Exports/Commands/IToggleInlineCommentMarginCommand.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.Exports/Settings/PkgCmdID.cs
  src/GitHub.InlineReviews/Commands/ToggleInlineCommentMarginCommand.cs
  src/GitHub.InlineReviews/GitHub.InlineReviews.csproj
  src/GitHub.InlineReviews/Glyph/GlyphMargin.cs
  src/GitHub.InlineReviews/InlineCommentMarginProvider.cs
  src/GitHub.InlineReviews/InlineReviewsPackage.cs
  src/GitHub.InlineReviews/InlineReviewsPackage.vsct
  src/GitHub.InlineReviews/Margins/InlineCommentMargin.cs
  src/GitHub.InlineReviews/Margins/InlineCommentMarginEnabled.cs
  src/GitHub.InlineReviews/Margins/InlineCommentMarginProvider.cs
  src/GitHub.InlineReviews/Margins/InlineCommentMarginVisible.cs
  src/GitHub.InlineReviews/Margins/InlineCommentTextViewOptions.cs
  src/GitHub.InlineReviews/Margins/PullRequestFileMargin.cs
  src/GitHub.InlineReviews/Margins/PullRequestFileMarginProvider.cs
  src/GitHub.InlineReviews/Services/PullRequestStatusBarManager.cs
  src/GitHub.InlineReviews/Tags/InlineCommentTagger.cs
  src/GitHub.InlineReviews/ViewModels/PullRequestFileMarginViewModel.cs
  src/GitHub.InlineReviews/Views/CommentView.xaml
  src/GitHub.InlineReviews/Views/PullRequestFileMarginView.xaml
  src/GitHub.InlineReviews/Views/PullRequestFileMarginView.xaml.cs
  src/GitHub.VisualStudio/Commands/GoToSolutionOrPullRequestFileCommand.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/GitHub.VisualStudio.vsct
  src/GitHub.VisualStudio/GitHubPackage.cs
  test/GitHub.InlineReviews.UnitTests/Tags/InlineCommentTaggerTests.cs
  test/UnitTests/GitHub.Exports.Reactive/Services/PullRequestEditorServiceTests.cs
Labels: Ready for Review, verified

#1645 Stop GitServiceHelper from depending on MEF
  src/GitHub.App/GitHub.App.csproj
  src/GitHub.App/SampleData/GitServiceDesigner.cs
  src/GitHub.App/SampleData/PullRequestCreationViewModelDesigner.cs
  src/GitHub.App/SampleData/SampleViewModels.cs
  src/GitHub.App/Services/GitClient.cs
  src/GitHub.Exports/Models/BranchModel.cs
  src/GitHub.Exports/Models/LocalRepositoryModel.cs
  src/GitHub.Exports/Models/RepositoryModel.cs
  src/GitHub.Exports/Services/GitService.cs
  src/GitHub.TeamFoundation.14/RegistryHelper.cs
  src/GitHub.TeamFoundation.14/Services/LocalRepositoryModelFactory.cs
  src/GitHub.TeamFoundation.15/RegistryHelper.cs
  src/GitHub.VisualStudio/Commands/LinkCommandBase.cs
  test/UnitTests/GitHub.App/Models/RepositoryModelTests.cs
  test/UnitTests/GitHub.App/Services/GitClientTests.cs
  test/UnitTests/GitHub.App/Services/PullRequestServiceTests.cs
  test/UnitTests/GitHub.Exports/LocalRepositoryModelTests.cs
Labels: bug

#1672 Adding functionality to the back button in the fork view
  src/GitHub.App/SampleData/ForkRepositoryExecuteViewModelDesigner.cs
  src/GitHub.App/ViewModels/Dialog/ForkRepositoryExecuteViewModel.cs
  src/GitHub.App/ViewModels/Dialog/ForkRepositoryViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/Dialog/IForkRepositoryExecuteViewModel.cs
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositoryExecuteView.xaml
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositoryExecuteView.xaml.cs
Labels: Ready for Review, verified

#1651 Disable MEF services that are derived from VS services when executing in Blend
  src/GitHub.Exports/Exports/ExportForProcessAttribute.cs
  src/GitHub.Exports/Exports/ExportForVisualStudioProcessAttribute.cs
  src/GitHub.Exports/GitHub.Exports.csproj
  src/GitHub.InlineReviews/InlineReviewsPackage.cs
  src/GitHub.TeamFoundation.14/Base/TeamExplorerServiceHolder.cs
  src/GitHub.VisualStudio.UI/Resources.Designer.cs
  src/GitHub.VisualStudio.UI/Resources.resx
  src/GitHub.VisualStudio/Commands/ShowMessageBoxCommand.cs
  src/GitHub.VisualStudio/GitContextPackage.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/GitHubPackage.cs
  src/GitHub.VisualStudio/Settings/OptionsPage.cs
Labels: Ready for Review, bug, verified

#1659 Limiting functionality in the beta repo fork functionality
  src/GitHub.App/Models/Account.cs
  src/GitHub.App/SampleData/ForkRepositoryExecuteViewModelDesigner.cs
  src/GitHub.App/SampleData/ForkRepositorySelectViewModelDesigner.cs
  src/GitHub.App/Services/RepositoryForkService.cs
  src/GitHub.App/ViewModels/Dialog/ForkRepositoryExecuteViewModel.cs
  src/GitHub.App/ViewModels/Dialog/ForkRepositorySelectViewModel.cs
  src/GitHub.App/ViewModels/Dialog/ForkRepositoryViewModel.cs
  src/GitHub.Exports.Reactive/ViewModels/Dialog/IForkRepositoryExecuteViewModel.cs
  src/GitHub.Exports/Models/UsageModel.cs
  src/GitHub.TeamFoundation.14/Home/ForkNavigationItem.cs
  src/GitHub.VisualStudio.UI/Base/TeamExplorerItemBase.cs
  src/GitHub.VisualStudio/GitHub.VisualStudio.csproj
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositoryExecuteView.xaml
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositoryExecuteView.xaml.cs
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositorySelectView.xaml
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositorySwitchView.xaml
  src/GitHub.VisualStudio/Views/Dialog/ForkRepositorySwitchView.xaml.cs
Labels: Ready for Review

#1699 Fix scrolling in PR details view.
  src/GitHub.UI/Controls/ScrollingVerticalStackPanel.cs
  src/GitHub.UI/GitHub.UI.csproj
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestDetailView.xaml
  src/GitHub.VisualStudio/Views/GitHubPane/PullRequestFilesView.xaml.cs
Labels: verified

#1687 Mark branch for created PR.
  src/GitHub.App/Services/PullRequestService.cs
  src/GitHub.App/Services/TeamExplorerContext.cs
  test/UnitTests/GitHub.App/Services/PullRequestServiceTests.cs
  test/UnitTests/GitHub.App/Services/TeamExplorerContextTests.cs
  test/UnitTests/GitHub.App/ViewModels/Dialog/PullRequestCreationViewModelTests.cs
Labels: verified
