Repository github/VisualStudio, pull requests merged in 2018-02, with the labels that each got.

#1478 Fix a bunch of warnings in release build
  src/GitHub.App/Api/ApiClient.cs
  src/GitHub.Logging/Logging/LogManager.cs
  test/GitHub.InlineReviews.UnitTests/TestDoubles/FakeDiffService.cs
  test/UnitTests/GitHub.Api/LoginManagerTests.cs
  test/UnitTests/GitHub.App/Caches/ImageCacheTests.cs
  test/UnitTests/GitHub.App/Models/AccountModelTests.cs
  test/UnitTests/GitHub.App/Services/GitClientTests.cs
  test/UnitTests/GitHub.App/Services/PullRequestServiceTests.cs
  test/UnitTests/GitHub.VisualStudio/Services/ConnectionManagerTests.cs
  test/UnitTests/TestDoubles/FakeCommitLog.cs
Labels: Ready for Review

#1451 Avoid need to execute SharedDictionaryManager test in app domain
  src/GitHub.UI/Helpers/SharedDictionaryManager.cs
  test/GitHub.UI.UnitTests/Helpers/SharedDictionaryManagerTests.cs
Labels: Ready for Review

#1480 Show progress of sync submodules command on the status bar
  src/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModel.cs
  test/UnitTests/GitHub.App/ViewModels/GitHubPane/PullRequestDetailViewModelTests.cs
Labels: Ready for Review

#1495 Tweak highlight colors
  src/GitHub.VisualStudio.UI/Styles/ThemeBlue.xaml
  src/GitHub.VisualStudio.UI/Styles/ThemeDark.xaml
  src/GitHub.VisualStudio.UI/Styles/ThemeLight.xaml
Labels: Ready for Review, cosmetic

#1499 Ensure correct ordering of VSGitExt.ActiveRepositoriesChanged.
  src/GitHub.App/Services/TeamExplorerContext.cs
  src/GitHub.App/ViewModels/GitHubPane/GitHubPaneViewModel.cs
  src/GitHub.TeamFoundation.14/Services/VSGitExt.cs
  test/UnitTests/GitHub.TeamFoundation/VSGitExtTests.cs
Labels: verified
